include: "modules/define.smk"



rule all:
	input: sm_temp_dir / "reports_complete"

if common_config["platform"] == "TempO-Seq":
	include: "modules/1-preprocess_temposeq.smk"

if common_config["platform"] == "RNA-Seq":
	include: "modules/1-preprocess_rnaseq.smk"

include: "modules/2-qc.smk"

include: "modules/3-diffexp_and_reports.smk"

