---
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
    theme: spacelab           # flatly spacelab sandstone cerulean
    code_download: true
---

Summary report of DEG analysis over all facets


```{r docSetup, warning = FALSE, message = FALSE, include = F}
#### Record start time
startTime <- Sys.time()

library('tidyverse')
library('devtools')
library('DESeq2')
library('data.table')
library('yaml')
library('stringr')
library(pheatmap)
library(RColorBrewer)
library(ComplexHeatmap)
library(circlize)

source(here::here("scripts","file_functions.R"))
source(here::here("scripts","setup_functions.R"))
source(here::here("scripts","DESeq_functions.R"), local = TRUE)

config <- yaml::read_yaml(file.path(here::here(),
                                    "config/config.yaml"),
                          eval.expr = T)

# Combine required params from config
params <- c(config$common, config$DESeq2)
# replace nulls in params with NA
params <- replace_nulls_in_config(params)
# If projectdir is not set, figure out current project root directory
projectdir <- params$projectdir
if (is.na(projectdir)) {
  projectdir <- here::here()
  params$projectdir <- projectdir
}



paths <- set_up_paths(params)
species_data <- load_species(params$species, params$wikipathways_filename, params$biospyder_manifest_file)
params$species_data <- species_data
params <- set_up_platform_params(params)

db <- AnnotationDbi::loadDb(dbfile(get(species_data$orgdb)))

# input data file
dataFile <- file.path(paths$RData, paste0(params$project_title, "_DEG_data.RData"))
load(dataFile) # metadata, contrasts, counts, resultsList

exp_metadata <- exp_metadata %>%
  mutate(uv_dosage_2 = factor(uv_dosage_2, levels = c( "Sham", "5_mJ_cm2", "10_mJ_cm2", "20_mJ_cm2", "40_mJ_cm2", "5pct_Oxalazone")))

```


```{r setup_dfs}
# set up unfaceted data objects


allResultsUnfaceted <- data.frame()
significantResultsUnfaceted <- data.frame()

ordered_contrasts <- paste0(contrasts$V1, " vs ", contrasts$V2)
ordered_levels <- expand.grid(facets,ordered_contrasts) %>% arrange(Var1) %>% mutate(asdf = paste0(Var1, ": ", Var2)) %>% pull(asdf)

for (f in facets){
  resultsListAll <- overallResListAll[[f]]
  resultsListDEGs <- overallResListDEGs[[f]]
  design <- designList[[f]]
  if (length(resultsListAll) > 0) {
    allResults <- annotate_deseq_table(resultsListAll, params, filter_results = F)
    allResultsUnfaceted <- allResults %>% mutate(facet=f) %>% rbind(allResultsUnfaceted)
  }
  if (length(resultsListDEGs) > 0) {
    significantResults <- annotate_deseq_table(resultsListDEGs, params, filter_results = F)
    significantResultsUnfaceted <- significantResults %>% mutate(facet=f) %>% rbind(significantResultsUnfaceted)
  }
}

```


Number of DEGs for each contrast tested

```{r p1}

p1_data <- significantResultsUnfaceted %>%
    mutate(facet_contrast = factor(paste0(facet, ": ", contrast), levels = ordered_levels))


if (length(facets) < 10) {
  plot_size = 5 
} else {
  plot_size = round(sqrt(length(facets)))*1.5
}

if(length(facets) == 1){
  p1 = ggplot(p1_data, aes(x=contrast)) +
    geom_bar(aes(y=..count..)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle=90, hjust=1)) +
    ylab("Number of DEGs") +
    xlab("Contrast")
} else if (length(facets) < 10) {
    p1 = ggplot(p1_data, aes(x=facet_contrast)) +
        geom_bar(aes(y=..count.., fill=facet)) +
        theme_bw() +
        theme(axis.text.x = element_text(angle=90, hjust=1)) +
        ylab("Number of DEGs") +
        xlab("Facet: contrast")
} else {
    p1 = ggplot(p1_data, aes(x=facet_contrast)) +
        geom_bar(aes(y=..count.., fill=facet)) +
        theme_bw() +
        theme(axis.text.x = element_blank(),
            legend.position = "none") +
        facet_wrap(~facet, scales = "free_x") +
        ylab("Number of DEGs") +
        xlab("Facet: contrast")
}

p1
```


Number of genes filtered by each R-ODAF filtering criterium


```{r p2}


# plot filter stats
p2_data <- filtered_table %>%
  group_by(facet,contrast) %>%
  mutate(not_significant = initial-(relevance_filtered+quantile_filtered+spike_filtered)) %>%
  mutate(contrast = str_replace(contrast, "_vs_", " vs ")) %>%
  ungroup() %>%
  pivot_longer(cols=c(not_significant,relevance_filtered,quantile_filtered,spike_filtered,passed_all_filters)) %>%
  mutate(perc = value/initial) %>%
  mutate(name = factor(name, levels=c("relevance_filtered", "not_significant", "quantile_filtered", "spike_filtered", "passed_all_filters"))) %>%
  mutate(facet_contrast = factor(paste0(facet, ": ", contrast), levels = ordered_levels))

if(length(facets) == 1){
  p2 = ggplot(p2_data, aes(x=contrast,y=value)) +
    theme_bw() +
    geom_bar(stat="identity",position="dodge") +
    facet_wrap(~name, scales="free") +
    theme(axis.text.x = element_text(angle=90, hjust=1)) +
    ylab("Percent of all reads") +
    xlab("Contrast")
  
} else if (length(facets) < 10) {
  p2 = ggplot(p2_data, aes(x=facet_contrast,y=value,fill=facet)) +
    theme_bw() +
    geom_bar(stat="identity",position="dodge") +
    facet_wrap(~name, scales="free") +
    theme(axis.text.x = element_text(angle=90, hjust=1)) +
    ylab("Percent of all reads") +
    xlab("Facet: contrast")
} else {
  p2 = ggplot(p2_data, aes(x=facet_contrast,y=value,fill=facet)) +
    theme_bw() +
    geom_bar(stat="identity",position="dodge") +
    facet_wrap(~name, scales="free") +
    theme(axis.text.x = element_blank(),
          legend.position = "none") +
    ylab("Percent of all reads") +
    xlab("Facet: contrast")
}
  
p2
```


Number of DEGs by group (grey indicates that group not tested)

```{r}

n_DEGs_data <- significantResultsUnfaceted %>%
  group_by(contrast) %>%
  summarise(n_DEGs = n()) %>%
  separate(contrast,c("group_1","group_2"),sep=" vs ", remove = FALSE) %>%
  left_join(exp_metadata, by=c("group_1"="condition")) %>%
  dplyr::select(n_DEGs,Timepoint_2 ,uv_dosage_2 ) %>%
  unique()

ggplot(n_DEGs_data, aes(x=Timepoint_2,y=n_DEGs)) +
  geom_bar(stat="identity") +
  facet_wrap(~uv_dosage_2) +
  theme(axis.text.x = element_text(angle=90, hjust=1))

ggplot(n_DEGs_data, aes(x=uv_dosage_2,y=n_DEGs)) +
  geom_bar(stat="identity") +
  facet_wrap(~Timepoint_2) +
  theme(axis.text.x = element_text(angle=90, hjust=1))

n_DEGs_mat <- n_DEGs_data %>%
  spread(uv_dosage_2, n_DEGs, fill=NA) %>%
#  pivot_wider(names_from="uv_dosage_2",values_from = "n_DEGs") %>%
  column_to_rownames(var="Timepoint_2") %>%
  as.matrix()

# TODO: assign breaks in a reasonable way

deg_breaks <- c(0,200,400,600,800,1000,1200,1400,1600,1800)
deg_colors <- colorRampPalette(rev(brewer.pal(n = 7, name = "YlGnBu")))(10)
#deg_breaks <- c(0,500,1000,1500)
#colors <- c("#666666", "#0C2C84","#41B6C4" , "#FFFFCC")

color_ramp <- colorRamp2(deg_breaks,deg_colors)

Heatmap(n_DEGs_mat,
         cluster_rows = FALSE,
         cluster_columns = FALSE,
         col = color_ramp
         )

```


```{r}

n_heatmap_genes <- 50 # number of genes to plot in the heatmap

data <- significantResultsUnfaceted %>%
  dplyr::select(-c(baseMean, linearFoldChange, lfcSE, pvalue, padj, facet) ) %>%
  pivot_wider(names_from="contrast",values_from = "log2FoldChange" ) %>%
  dplyr::select(-Ensembl_Gene_ID, -Gene_Symbol) %>%
  column_to_rownames(var="Feature_ID") %>%
  mutate(nonzero_count=rowSums(.!=0)) %>%
  arrange(desc(nonzero_count)) %>% 
  head(n_heatmap_genes) %>%
  dplyr::select(-nonzero_count)

heatmap_genes <- rownames(data)

data_all <- allResultsUnfaceted %>%
  filter(Feature_ID %in% heatmap_genes) %>%
  dplyr::select(-c(baseMean, linearFoldChange, lfcSE, pvalue, padj, facet) ) %>%
  pivot_wider(names_from="contrast",values_from = "log2FoldChange" ) %>%
  dplyr::select(-Ensembl_Gene_ID, -Gene_Symbol) %>%
  column_to_rownames(var="Feature_ID")


data_mat <- as.matrix(data)
data_all_mat <- as.matrix(data_all)

highlight_significant <- function(j, i, x, y, width, height, fill) {
          cont <- colnames(data_all_mat)[j]
          feat <- rownames(data_all_mat)[i]
          sig_results <- significantResultsUnfaceted[significantResultsUnfaceted$contrast == cont & significantResultsUnfaceted$Feature_ID == feat,]
          if(nrow(sig_results) > 0){
            grid.rect(x,y,width,height,gp=gpar(col="green", fill=NA))
          }
        }

Heatmap(data_all_mat,
        cluster_columns=F,
        cell_fun = highlight_significant)

```


```{r}

bestGenes <- significantResultsUnfaceted %>%
  sample_n(10) %>%
  pull(Feature_ID)

allBestData <- allResultsUnfaceted %>%
    filter(Feature_ID %in% bestGenes) %>%
    pull(log2FoldChange)



for(g in bestGenes){
  FC_mat <- allResultsUnfaceted %>%
    filter(Feature_ID == g) %>%
    separate(contrast,c("group_1","group_2"),sep=" vs ", remove = FALSE) %>%
    left_join(exp_metadata, by=c("group_1"="condition")) %>%
    dplyr::select(log2FoldChange,uv_dosage_2,Timepoint_2) %>%
    unique() %>%
    spread(uv_dosage_2,log2FoldChange) %>%
#    pivot_wider(names_from="uv_dosage_2",values_from = "log2FoldChange") %>%
    column_to_rownames(var="Timepoint_2") %>%
    as.matrix()
  
  highlight_significant <- function(j, i, x, y, width, height, fill) {
            cont <- paste0(colnames(FC_mat)[j],"_",rownames(FC_mat)[i]," vs Sham_",rownames(FC_mat)[i])
            feat <- g
            sig_results <- significantResultsUnfaceted[significantResultsUnfaceted$contrast == cont & significantResultsUnfaceted$Feature_ID == feat,]
            if(nrow(sig_results) > 0){
              grid.rect(x,y,width,height,gp=gpar(col="green", fill=NA))
            }
          }

  
  paletteLength <- 9
  colours <- colorRampPalette(c("yellow", "white", "blue"))(paletteLength)
  breaks <- c(seq(min(allBestData), 0, length.out=ceiling(paletteLength/2) + 1), 
                seq(max(allBestData)/paletteLength, max(allBestData), length.out=floor(paletteLength/2)))

  col_fun = colorRamp2(c(-2, 0, 2), c("yellow", "white", "blue"))

  
  
  cat(g)
  print(
  Heatmap(FC_mat,
          cluster_rows = FALSE,
          cluster_columns = FALSE,
          col = col_fun
           )
  )
}

```