version: '3.3'

services:
  r-odaf:
          #restart: "unless-stopped"
    container_name: R-ODAF
    volumes:
      - ./inputs:/home/R-ODAF/R-ODAF_Health_Canada/inputs
      - ./output:/home/R-ODAF/R-ODAF_Health_Canada/output
      #- ./reference:/home/R-ODAF/R-ODAF_Health_Canada/reference
      #- ./wikipathways-20210810-gmt-Homo_sapiens.gmt:/home/R-ODAF/R-ODAF_Health_Canada/wikipathways-20210810-gmt-Homo_sapiens.gmt
      #- ./Human_S1500_1.2_standardized.csv:/home/R-ODAF/R-ODAF_Health_Canada/Human_S1500_1.2_standardized.csv 
    image: r-odaf:latest
    # command: /bin/bash -l
    environment:
      - HOST_UID=10007
      - HOST_GID=10008
    tty: true

  rstudio:
    image: rocker/tidyverse
    restart: "unless-stopped"
    container_name: rstudio-server-odaf
    volumes_from:
      - r-odaf
    ports:
      - 8790:8787
    environment:
      - R_LIBS=${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library'}
      - PASSWORD=changeme

  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    volumes_from:
      - r-odaf
        #command: /opt/conda/bin/jupyter notebook --ip=0.0.0.0 --port=8888 --notebook-dir=/home/R-ODAF/ --allow-root --no-browser
    ports:
      - 11111:8888

