########################################################
## Build R-ODAF container for transcriptomic analysis ##
########################################################
# R-ODAF base image
# Run tests using base dependencies, but updated code
# Note that if you alter any dependencies, the base container must be rebuilt
FROM mattjmeier/r-odaf-hc-base

# Update code if it has changed in build context
COPY . . 
USER root
RUN chown -R R-ODAF:R-ODAF /home/R-ODAF
USER R-ODAF

RUN /bin/bash -c "snakemake --cores 32 --use-conda"

# Clean up directories
RUN mkdir tests \
&& mv analysis/ \
test-data/ \
truth_checksums/ \
wikipathways-20210810-gmt-Homo_sapiens.gmt  \
Human_S1500_1.2_standardized.csv \
logs/ \
data/ \
config \
tests \
&& mv data.bak data && mv config.bak config

