chooseCRANmirror(1, graphics=FALSE)


install.packages("tidyverse")
install.packages("yaml")
install.packages("plotly")
install.packages("data.table")
install.packages("cluster")
install.packages("Cairo")
install.packages("sfsmisc")
install.packages("fields")
install.packages("heatmap3")
install.packages("foreach")
install.packages("doParallel")
install.packages("UpSetR")
install.packages("GGally")
install.packages("pheatmap")
install.packages("kableExtra")
install.packages("dendextend")
install.packages("dendsort")
install.packages("rrcov")
install.packages("cellWise")
install.packages("vtree")
install.packages("knitr")
install.packages("magrittr")
install.packages("DT")
install.packages("lattice")
install.packages("tidytext")
install.packages("openxlsx")
install.packages("RColorBrewer")
install.packages("viridis")
install.packages("sessioninfo")
install.packages("gtools")
install.packages("ggridges")
install.packages("crosstalk")
install.packages("crosstool")


install.packages("BiocManager")

BiocManager::install("QuasR")
BiocManager::install("rtracklayer")
BiocManager::install("GenomicFeatures")
BiocManager::install("edgeR")
BiocManager::install("DESeq2")
BiocManager::install("ComplexHeatmap")
BiocManager::install("limma")
BiocManager::install("enrichplot")
BiocManager::install("rWikiPathways")
BiocManager::install("BiocParallel")
BiocManager::install("clusterProfiler")
BiocManager::install("biomaRt")
BiocManager::install("AnnotationHub")
BiocManager::install("vsn")


